import type { Article, HomeContent, SiteSettings } from './types'
import type { Locale } from '@/i18n/config'

export const fallbackSettings: Record<Locale, SiteSettings> = {
  de: {
    companyName: 'East Asia Power Construction Co., Ltd.',
    contact: {
      address: '173 Changjiang South Street, Huanggu District, Shenyang, Liaoning, China',
      email: 'contact@eastasiapower.example',
    },
    footerLinks: [
      { href: '/#solutions', label: 'Lösungen' },
      { href: '/#projects', label: 'Projektbelege' },
      { href: '/news', label: 'Informationen' },
      { href: 'mailto:contact@eastasiapower.example', label: 'Kontakt' },
    ],
    navigation: [
      { href: '/#solutions', label: 'Lösungen' },
      { href: '/#projects', label: 'Projektbelege' },
      { href: '/news', label: 'Informationen' },
      { href: '/#company', label: 'Unternehmen' },
    ],
    seo: {
      description:
        'East Asia Power Construction Co., Ltd. ist ein Strombau- und Energieinfrastrukturunternehmen aus Shenyang mit öffentlichen Qualifikationen und Projektbelegen.',
      title: 'East Asia Power Construction Co., Ltd. | Strombau und Energieinfrastruktur',
    },
    tagline:
      'Strombau, Anlageninstallation, technische Dienstleistungen und erneuerbare Energietechnik aus Shenyang.',
  },
  en: {
    companyName: 'East Asia Power Construction Co., Ltd.',
    contact: {
      address: '173 Changjiang South Street, Huanggu District, Shenyang, Liaoning, China',
      email: 'contact@eastasiapower.example',
    },
    footerLinks: [
      { href: '/#solutions', label: 'Solutions' },
      { href: '/#projects', label: 'Project records' },
      { href: '/news', label: 'Information' },
      { href: 'mailto:contact@eastasiapower.example', label: 'Contact' },
    ],
    navigation: [
      { href: '/#solutions', label: 'Solutions' },
      { href: '/#projects', label: 'Project records' },
      { href: '/news', label: 'Information' },
      { href: '/#company', label: 'Company' },
    ],
    seo: {
      description:
        'East Asia Power Construction Co., Ltd. is a Shenyang-based power engineering and energy infrastructure contractor with public qualifications and project records.',
      title: 'East Asia Power Construction Co., Ltd. | Power engineering and energy infrastructure',
    },
    tagline:
      'Power construction, electrical installation, engineering services, and renewable-energy technology from Shenyang.',
  },
  zh: {
    companyName: '东亚电力建设有限公司',
    contact: {
      address: '辽宁省沈阳市皇姑区长江南街173号',
      email: 'contact@eastasiapower.example',
    },
    footerLinks: [
      { href: '/#solutions', label: '解决方案' },
      { href: '/#projects', label: '项目记录' },
      { href: '/news', label: '资料' },
      { href: 'mailto:contact@eastasiapower.example', label: '联系' },
    ],
    navigation: [
      { href: '/#solutions', label: '解决方案' },
      { href: '/#projects', label: '项目记录' },
      { href: '/news', label: '资料' },
      { href: '/#company', label: '公司' },
    ],
    seo: {
      description:
        '东亚电力建设有限公司是位于沈阳的电力工程与能源基础设施企业，公开资料显示具备电力工程、建筑工程和电力设施相关资质与项目记录。',
      title: '东亚电力建设有限公司 | 电力工程与能源基础设施服务',
    },
    tagline: '立足沈阳，面向电力工程施工、电气安装、工程技术服务与新能源技术应用。',
  },
}

export const fallbackHome: Record<Locale, HomeContent> = {
  de: {
    cta: {
      body: 'Sprechen Sie mit unserem Team über Strombau, technische Sanierung, Anlageninstallation und erneuerbare Energieanwendungen.',
      headline: 'Projektanforderungen früh klären, Ausführung stabil steuern.',
      href: 'mailto:contact@eastasiapower.example',
      label: 'Kontakt aufnehmen',
    },
    deploymentHighlights: [
      { label: 'öffentliche Ausschreibungs- und Zuschlagsdatensätze', value: '97' },
      { label: 'Bau- und Strombauqualifikation D221023703 gültig bis', value: '2029' },
    ],
    gridSceneSteps: [
      {
        body: 'Der Spitzenbedarf in Texas dürfte sich bis 2030 gegenüber heute verdoppeln, getrieben durch KI-Rechenzentren, Industrieausbau und Elektrifizierung, die den Netzausbau überholen.',
        capacity: '77/85',
        kind: 'challenge',
        label: 'Herausforderung',
        number: 1,
        progress: 91,
        title: 'Volatiles Marktdesign',
      },
      {
        body: 'Wir bauen dezentrale Speicherstandorte nahe am Bedarf. Lokale Anlagen entlasten Engpässe, stabilisieren das Netz in der Nähe und schaffen systemweit mehr Wert.',
        capacity: '68/85',
        kind: 'solution',
        label: 'Lösung',
        number: 1,
        progress: 80,
        title: 'Netzentlastung durch lokale Speicher',
      },
      {
        body: 'Ohne Kapazitätsverträge stützt sich der Markt auf Preise. Kosten können von normalen Betriebsniveaus bis in Knappheitsereignisse ausschlagen.',
        capacity: '84/85',
        kind: 'challenge',
        label: 'Herausforderung',
        number: 2,
        progress: 98,
        title: 'Knappheitspreisereignisse',
      },
      {
        body: 'Speicher lädt bei günstiger Energie und entlädt in Knappheitsphasen, reduziert Preisspitzen und verbessert die Systemzuverlässigkeit.',
        capacity: '70/85',
        kind: 'solution',
        label: 'Lösung',
        number: 2,
        progress: 82,
        title: 'Netzreaktiver Speicher',
      },
      {
        body: 'Solar- und Windleistung passt nicht immer zur Nachfrage. Ohne Speicher bleibt erneuerbare Energie ungenutzt oder wird abgeregelt.',
        capacity: '59/85',
        kind: 'challenge',
        label: 'Herausforderung',
        number: 3,
        progress: 69,
        title: 'Erneuerbare ohne Flexibilität',
      },
      {
        body: 'Speicher nimmt überschüssigen Wind- und Solarstrom auf und gibt ihn zu Spitzenzeiten zurück, sodass variable Erzeugung zu verlässlicher Versorgung wird.',
        capacity: '64/85',
        kind: 'solution',
        label: 'Lösung',
        number: 3,
        progress: 75,
        title: 'Saubere Flexibilität',
      },
    ],
    hero: {
      headline: 'Strombau und Energieinfrastruktur mit nachprüfbarer Ausführung',
      primaryCtaLabel: 'Kontakt aufnehmen',
      secondaryCtaLabel: 'Projektinformationen lesen',
      subline:
        'East Asia Power Construction Co., Ltd. verbindet Strombau, elektrische Installation, Engineering-Management und erneuerbare Energietechnik für Industrie-, Netz- und öffentliche Infrastrukturprojekte.',
    },
    locale: 'de',
    proofPoints: [
      { label: 'Gründung laut öffentlicher Registrierung', value: '2002' },
      { label: 'registriertes Kapital, Mio. RMB', value: '120' },
      { label: 'Bau- und Strombauqualifikation', value: 'D221023703' },
      { label: 'öffentliche Zuschlags- und Projektdatensätze', value: '97' },
    ],
    statement: {
      headline: 'Seit 2002 auf Strombau, Installation und technische Ausführung ausgerichtet.',
      lead: 'Öffentliche Informationen zeigen ein in Shenyang registriertes Unternehmen mit Strombau-, Bau-, Elektroinstallations-, Versorgungsanlagen- und erneuerbare-Energie-Bezug. Die Website stellt diese nachprüfbaren Informationen sachlich zusammen.',
    },
    storyItems: [
      {
        body: 'Industrie, öffentliche Einrichtungen und Energieanlagen benötigen stabile Stromversorgung, klare Bauorganisation und nachvollziehbare Qualifikationen.',
        kind: 'challenge',
        metricLabel: 'Gründung',
        metricValue: '2002',
        number: 1,
        title: 'Zuverlässige Strominfrastruktur',
      },
      {
        body: 'Das Leistungsprofil umfasst Strombau, elektrische Installation, Engineering-Management, technische Dienstleistungen sowie Installation, Reparatur und Prüfung von Stromanlagen.',
        kind: 'solution',
        metricLabel: 'registriertes Kapital',
        metricUnit: 'Mio. RMB',
        metricValue: '120',
        number: 1,
        title: 'Ausführung über mehrere Gewerke',
      },
      {
        body: 'Ältere Transformatoren, Schaltgeräte und Verteilanlagen müssen unter laufenden Betriebsbedingungen geprüft, ersetzt oder modernisiert werden.',
        kind: 'challenge',
        metricLabel: 'Beispiel-Projektjahr',
        metricValue: '2025',
        number: 2,
        title: 'Sanierung unter Betriebsdruck',
      },
      {
        body: 'Öffentliche Projektdatensätze nennen unter anderem Transformatorprüfung, Austausch von Schaltgeräten und Standortarbeiten an Wind- und PV-Anlagen in Liaoning.',
        kind: 'solution',
        metricLabel: 'Projektwert',
        metricUnit: '10k RMB',
        metricValue: '29.2975',
        number: 2,
        title: 'Betriebsnahe Servicefähigkeit',
      },
      {
        body: 'Photovoltaik, Windenergie und Wärmeversorgung stellen neue Anforderungen an Netzzugang, Baukoordination und technische Sicherheit.',
        kind: 'challenge',
        metricLabel: 'Patentveröffentlichung',
        metricValue: 'CN215010107U',
        number: 3,
        title: 'Energieprojekte werden hybrider',
      },
      {
        body: 'Ein öffentliches Patent des Unternehmens behandelt einen Photovoltaik- und Wind-Hybridtunnel für die Stromversorgung elektrischer Lokomotiven und zeigt die technische Erweiterung in erneuerbare Anwendungen.',
        kind: 'solution',
        metricLabel: 'veröffentlicht',
        metricValue: '2021',
        number: 3,
        title: 'Technische Erweiterung in erneuerbare Energien',
      },
    ],
  },
  en: {
    cta: {
      body: 'Talk to our team about power construction, technical retrofit, electrical installation, and renewable-energy applications.',
      headline: 'Clarify project requirements early and keep delivery controlled.',
      href: 'mailto:contact@eastasiapower.example',
      label: 'Get in touch',
    },
    deploymentHighlights: [
      { label: 'public bid and award records indexed online', value: '97' },
      { label: 'construction and power qualification D221023703 valid to', value: '2029' },
    ],
    gridSceneSteps: [
      {
        body: 'Peak demand in Texas is expected to double between now and 2030, driven by AI data centers, industrial expansion, and electrification outpacing new transmission capacity.',
        capacity: '77/85',
        kind: 'challenge',
        label: 'Challenge',
        number: 1,
        progress: 91,
        title: 'Volatile Market Design',
      },
      {
        body: 'We built distributed storage sites close to demand. Local assets relieve congestion, balance the grid nearby, and deliver more value system-wide.',
        capacity: '68/85',
        kind: 'solution',
        label: 'Solution',
        number: 1,
        progress: 80,
        title: 'Relieving the Grid with Local Storage',
      },
      {
        body: 'With no capacity contracts, the market relies on price. Costs can swing from normal operating levels into scarcity events.',
        capacity: '84/85',
        kind: 'challenge',
        label: 'Challenge',
        number: 2,
        progress: 98,
        title: 'Scarcity Price Events',
      },
      {
        body: 'Storage charges when energy is cheap and discharges during scarcity, reducing price spikes and improving system reliability.',
        capacity: '70/85',
        kind: 'solution',
        label: 'Solution',
        number: 2,
        progress: 82,
        title: 'Grid-Responsive Storage',
      },
      {
        body: 'Solar and wind output does not always match demand. Without storage, renewable energy is stranded or curtailed.',
        capacity: '59/85',
        kind: 'challenge',
        label: 'Challenge',
        number: 3,
        progress: 69,
        title: 'Renewables Without Flexibility',
      },
      {
        body: 'Storage captures surplus wind and solar and returns it during peak hours, turning variable generation into dependable supply.',
        capacity: '64/85',
        kind: 'solution',
        label: 'Solution',
        number: 3,
        progress: 75,
        title: 'Clean Flexibility',
      },
    ],
    hero: {
      headline: 'Power engineering and energy infrastructure with traceable delivery records',
      primaryCtaLabel: 'Get in touch',
      secondaryCtaLabel: 'Read project information',
      subline:
        'East Asia Power Construction Co., Ltd. brings together power construction, electrical installation, engineering management, and renewable-energy technology for industrial, grid, and public infrastructure work.',
    },
    locale: 'en',
    proofPoints: [
      { label: 'founded according to public registration records', value: '2002' },
      { label: 'registered capital, RMB million', value: '120' },
      { label: 'construction and power qualification', value: 'D221023703' },
      { label: 'public award and project records indexed online', value: '97' },
    ],
    statement: {
      headline: 'Focused on power construction, installation, and technical delivery since 2002.',
      lead: 'Public information shows a Shenyang-registered company covering power engineering, construction, electrical installation, utility facilities, and renewable-energy services. This site organizes those verifiable facts into clear business content.',
    },
    storyItems: [
      {
        body: 'Industrial sites, public facilities, and energy assets need stable power supply, clear construction control, and qualified delivery partners.',
        kind: 'challenge',
        metricLabel: 'Founded',
        metricValue: '2002',
        number: 1,
        title: 'Reliable power infrastructure',
      },
      {
        body: 'The public business scope covers power construction, electrical installation, engineering management, technical services, and installation, repair, and testing of power facilities.',
        kind: 'solution',
        metricLabel: 'Registered capital',
        metricUnit: 'RMB mn',
        metricValue: '120',
        number: 1,
        title: 'Multi-discipline execution',
      },
      {
        body: 'Ageing transformers, switching equipment, and distribution facilities have to be inspected, replaced, or upgraded while operations continue.',
        kind: 'challenge',
        metricLabel: 'Example project year',
        metricValue: '2025',
        number: 2,
        title: 'Retrofit under operating pressure',
      },
      {
        body: 'Public project records include transformer testing, switching-device replacement, and site works for wind and photovoltaic assets in Liaoning.',
        kind: 'solution',
        metricLabel: 'Project value',
        metricUnit: 'RMB 10k',
        metricValue: '29.2975',
        number: 2,
        title: 'Operational service capability',
      },
      {
        body: 'Photovoltaic, wind, and heating-supply projects create new requirements for grid connection, construction coordination, and technical safety.',
        kind: 'challenge',
        metricLabel: 'Patent publication',
        metricValue: 'CN215010107U',
        number: 3,
        title: 'Energy projects are becoming hybrid',
      },
      {
        body: 'A public patent assigned to the company describes a photovoltaic and wind hybrid generation tunnel for electric locomotives, showing a technical extension into renewable applications.',
        kind: 'solution',
        metricLabel: 'Published',
        metricValue: '2021',
        number: 3,
        title: 'Renewable-energy technology extension',
      },
    ],
  },
  zh: {
    cta: {
      body: '可围绕电力工程施工、变配电改造、电气安装、工程技术服务与新能源应用进行项目沟通。',
      headline: '把项目需求前置梳理，把施工交付稳定推进。',
      href: 'mailto:contact@eastasiapower.example',
      label: '联系东亚电力',
    },
    deploymentHighlights: [
      { label: '公开中标成交记录索引', value: '97' },
      { label: '建筑与电力工程资质 D221023703 有效至', value: '2029' },
    ],
    gridSceneSteps: [
      {
        body: '受 AI 数据中心、工业扩张和电气化需求推动，新增输电能力跟不上增长节奏，得州峰值用电需求预计到 2030 年将较当前翻倍。',
        capacity: '77/85',
        kind: 'challenge',
        label: '挑战',
        number: 1,
        progress: 91,
        title: '波动的市场设计',
      },
      {
        body: '我们在靠近负荷的位置建设分布式储能站点。本地资产能够缓解拥堵，就近平衡电网，并在系统层面释放更高价值。',
        capacity: '68/85',
        kind: 'solution',
        label: '方案',
        number: 1,
        progress: 80,
        title: '用本地储能缓解电网压力',
      },
      {
        body: '在没有容量合约的情况下，市场主要依赖价格信号。成本可能从正常运行水平快速跃升至稀缺事件水平。',
        capacity: '84/85',
        kind: 'challenge',
        label: '挑战',
        number: 2,
        progress: 98,
        title: '稀缺电价事件',
      },
      {
        body: '储能在电价较低时充电，在供应紧张时放电，从而削弱价格尖峰并提升系统可靠性。',
        capacity: '70/85',
        kind: 'solution',
        label: '方案',
        number: 2,
        progress: 82,
        title: '响应电网的储能',
      },
      {
        body: '光伏和风电出力并不总是与用电需求同步。缺少储能时，可再生能源可能被滞留或弃用。',
        capacity: '59/85',
        kind: 'challenge',
        label: '挑战',
        number: 3,
        progress: 69,
        title: '缺少灵活性的可再生能源',
      },
      {
        body: '储能吸收富余风电和光伏电量，并在高峰时段释放，把波动性发电转化为更可靠的供应。',
        capacity: '64/85',
        kind: 'solution',
        label: '方案',
        number: 3,
        progress: 75,
        title: '清洁灵活性',
      },
    ],
    hero: {
      headline: '有公开资质与项目记录支撑的电力工程服务',
      primaryCtaLabel: '联系东亚电力',
      secondaryCtaLabel: '查看项目资料',
      subline:
        '东亚电力建设有限公司立足沈阳，围绕电力工程施工、电气安装、工程管理、工程技术服务与新能源技术应用，为工业、园区、市政和能源资产提供基础设施服务。',
    },
    locale: 'zh',
    proofPoints: [
      { label: '公开登记成立时间', value: '2002' },
      { label: '注册资本，百万元人民币', value: '120' },
      { label: '建筑与电力工程资质证书', value: 'D221023703' },
      { label: '公开中标成交与项目记录索引', value: '97' },
    ],
    statement: {
      headline: '自 2002 年起，聚焦电力工程、安装与技术交付。',
      lead: '公开资料显示，公司登记于沈阳，经营范围覆盖建设工程施工、电气安装服务、输配供电相关业务、电力设施安装维修试验、工程管理、工程技术服务、太阳能发电技术服务与热力生产供应等方向。本站内容按可查证资料进行整理。',
    },
    storyItems: [
      {
        body: '工业园区、公共建筑和能源资产需要稳定供电、清晰的施工组织，以及具备资质和项目经验的交付团队。',
        kind: 'challenge',
        metricLabel: '成立时间',
        metricValue: '2002',
        number: 1,
        title: '可靠电力基础设施',
      },
      {
        body: '公司公开经营范围覆盖电力工程施工、电气安装、工程管理、工程技术服务，以及电力设施安装、维修和试验。',
        kind: 'solution',
        metricLabel: '注册资本',
        metricUnit: '百万元人民币',
        metricValue: '120',
        number: 1,
        title: '跨专业施工交付能力',
      },
      {
        body: '老旧变压器、跌落式开关、配电设备和站区设施需要在不停产、不停运或短窗口条件下完成检测、更换和改造。',
        kind: 'challenge',
        metricLabel: '项目记录年份',
        metricValue: '2025',
        number: 2,
        title: '运行压力下的设备改造',
      },
      {
        body: '公开项目记录包含换热站变压器检测及跌落式更换、辽宁风电场和光伏电站设备区域现场维护等内容。',
        kind: 'solution',
        metricLabel: '成交金额',
        metricUnit: '万元',
        metricValue: '29.2975',
        number: 2,
        title: '贴近运行现场的服务',
      },
      {
        body: '光伏、风电和供热业务对并网、施工协调和设备安全提出更多复合要求，工程公司需要把传统施工与新能源技术结合起来。',
        kind: 'challenge',
        metricLabel: '专利公开号',
        metricValue: 'CN215010107U',
        number: 3,
        title: '能源项目正在复合化',
      },
      {
        body: '公司名下公开专利涉及“给铁路电力机车供电的光伏和风力互补发电隧道”，体现其在风光互补与交通能源场景上的技术延伸。',
        kind: 'solution',
        metricLabel: '公开时间',
        metricValue: '2021',
        number: 3,
        title: '新能源技术延伸',
      },
    ],
  },
}

export const fallbackArticles: Record<Locale, Article[]> = {
  de: [
    {
      body: 'Öffentliche Unternehmensinformationen nennen East Asia Power Construction Co., Ltd. als in Shenyang registriertes Unternehmen mit Gründung am 6. November 2002, einheitlichem Sozialkreditcode 9121010674272549XL und registriertem Kapital von 120 Mio. RMB.\n\nDer veröffentlichte Geschäftsbereich umfasst unter anderem Bauausführung, elektrische Installation, Stromerzeugung, Übertragung, Verteilung und Versorgung, Installation, Reparatur und Prüfung von Stromanlagen, Engineering-Management, technische Dienstleistungen, Solarenergietechnik, Wärmeversorgung sowie Waren- und Technologieimport und -export.\n\nFür die Website wird daraus kein überzogener Werbetext, sondern eine klare Positionierung: ein regional verankertes Unternehmen für Strombau, Anlageninstallation, technische Sanierung und Energieinfrastruktur.',
      category: 'company',
      excerpt: 'Registrierung, Geschäftsbereich und Positionierung des Unternehmens.',
      publishedAt: '2026-05-06T00:00:00.000Z',
      slug: 'company-registration-profile',
      title: 'Unternehmensprofil: Registrierung, Umfang und Positionierung',
    },
    {
      body: "Öffentliche Ausschreibungs- und Projektdatensätze nennen mehrere nachverfolgbare Referenzen. Dazu gehören die Transformatorprüfung und der Austausch von Schaltgeräten für die Nanfen Haocheng Wärmestation im Jahr 2025 sowie ein Projekt für die Entfernung von Bewuchs in Anlagenbereichen von Windparks und Photovoltaikstationen der Huaneng New Energy Liaoning Branch im Jahr 2024.\n\nÄltere Bauprojektdatensätze nennen außerdem das neue Häftlingsgebäude der Liaoning Women's Prison und eine Umsiedlungswohnanlage am Yulin Street Standort der Shenyang Automobile City. Die Einträge werden als öffentliche Projektbelege behandelt, nicht als vollständige Projektliste.\n\nFür Kunden ist der wichtigste Punkt: Die veröffentlichten Einträge decken sowohl Stromanlagen- und Betriebsservice als auch Bauausführung ab.",
      category: 'company',
      excerpt: 'Öffentlich auffindbare Projekt- und Zuschlagsdatensätze sachlich eingeordnet.',
      publishedAt: '2026-05-05T00:00:00.000Z',
      slug: 'public-project-records',
      title: 'Öffentliche Projektbelege: Stromanlagen, Standortservice und Bauausführung',
    },
    {
      body: 'Qualifikationsdaten zeigen für das Zertifikat D221023703 unter anderem Bauausführung und Strombau jeweils in Klasse II mit Gültigkeit bis 23. Juli 2029. Eine Bekanntmachung der Northeast Regional Administration der National Energy Administration führt East Asia Power Construction Co., Ltd. zudem in einem Verfahren zur Änderung der Lizenz für die Installation, Reparatur und Prüfung von Stromanlagen.\n\nTechnologisch ist auch das Patent CN215010107U relevant. Es beschreibt einen Photovoltaik- und Wind-Hybridtunnel zur Stromversorgung elektrischer Lokomotiven und zeigt, dass das Unternehmen erneuerbare Energieanwendungen in konkrete Infrastrukturszenarien übersetzt.\n\nDie Website nutzt diese Informationen, um die Leistungsfelder Strombau, elektrische Installation, Anlagenprüfung und erneuerbare Energieanwendungen konsistent darzustellen.',
      category: 'technology',
      excerpt: 'Qualifikationen und ein öffentliches Patent zeigen die technische Breite.',
      publishedAt: '2026-05-04T00:00:00.000Z',
      slug: 'qualification-and-renewable-technology',
      title: 'Qualifikationen und erneuerbare Energietechnik',
    },
  ],
  en: [
    {
      body: 'Public company information identifies East Asia Power Construction Co., Ltd. as a Shenyang-registered enterprise founded on November 6, 2002, with unified social credit code 9121010674272549XL and registered capital of RMB 120 million.\n\nThe published business scope covers construction engineering, electrical installation, power generation, transmission, distribution and supply, installation, repair and testing of power facilities, engineering management, technical services, solar power technology, heating supply, and import and export of goods and technology.\n\nFor the website, that becomes a factual positioning rather than inflated marketing: a regional power engineering company serving power construction, facility installation, technical retrofit, and energy infrastructure delivery.',
      category: 'company',
      excerpt: 'Registration, business scope, and practical positioning for the company.',
      publishedAt: '2026-05-06T00:00:00.000Z',
      slug: 'company-registration-profile',
      title: 'Company profile: registration, scope, and positioning',
    },
    {
      body: "Public bid and project indexes list several traceable references. These include transformer testing and switching-device replacement for the Nanfen Haocheng heat exchange station in 2025, and vegetation removal in equipment areas of wind farms and photovoltaic stations under Huaneng New Energy Liaoning Branch in 2024.\n\nOlder construction-market records also list the new prisoner housing project at Liaoning Women's Prison and a resettlement housing project in Shenyang Automobile City on Yulin Street. These entries are treated as public project records, not as a complete portfolio.\n\nFor customers, the useful message is direct: the public records touch both power-facility service and general construction execution.",
      category: 'company',
      excerpt: 'Publicly visible project and award records, presented with conservative wording.',
      publishedAt: '2026-05-05T00:00:00.000Z',
      slug: 'public-project-records',
      title: 'Public project records: power facilities, site services, and construction',
    },
    {
      body: 'Qualification records show certificate D221023703 for Grade II construction and power engineering qualifications, with validity to July 23, 2029. A public notice from the Northeast Regional Administration of the National Energy Administration also lists East Asia Power Construction Co., Ltd. in a change filing for the license covering installation, repair, and testing of power facilities.\n\nOn the technology side, patent CN215010107U describes a photovoltaic and wind hybrid generation tunnel for electric locomotives. It is a useful signal that the company connects renewable-energy ideas with physical infrastructure scenarios.\n\nThe site content uses these facts to present the company consistently across power construction, electrical installation, facility testing, and renewable-energy applications.',
      category: 'technology',
      excerpt: "Qualifications and a public patent show the company's technical range.",
      publishedAt: '2026-05-04T00:00:00.000Z',
      slug: 'qualification-and-renewable-technology',
      title: 'Qualifications and renewable-energy technology',
    },
  ],
  zh: [
    {
      body: '公开企业信息显示，东亚电力建设有限公司登记地为辽宁省沈阳市，成立于 2002 年 11 月 6 日，统一社会信用代码为 9121010674272549XL，注册资本 12000 万元。\n\n公开经营范围覆盖建设工程施工、电气安装服务、发电业务、输电业务、供配电业务、受电电力设施安装维修试验、工程管理服务、工程技术服务、太阳能发电技术服务、热力生产和供应、货物进出口和技术进出口等方向。\n\n因此，官网内容不再写成泛泛的“储能平台”或空泛能源公司，而是定位为立足沈阳的电力工程、设施安装、技术改造与能源基础设施服务企业。',
      category: 'company',
      excerpt: '整理公司登记信息、经营范围和官网定位。',
      publishedAt: '2026-05-06T00:00:00.000Z',
      slug: 'company-registration-profile',
      title: '公司概览：登记信息、经营范围与官网定位',
    },
    {
      body: '公开中标与项目索引中，可以检索到若干与东亚电力建设有限公司相关的记录。例如 2025 年的“南芬昊诚换热站变压器检测跌落式更换”，以及 2024 年的“华能新能源辽宁分公司下属风电场光伏电站设备区域杂草铲除工程”，后者公开金额为 29.2975 万元。\n\n较早的建筑市场项目记录还包含“辽宁省女子监狱新建罪犯用房项目”和“沈阳荣安房地产开发有限公司沈阳汽车城榆林大街安置房一期（07号地块）”等。这里将其作为公开项目记录呈现，不等同于完整业绩清单。\n\n这些记录反映出公司服务面既包括电力设施检测、更换、现场维护，也覆盖建筑工程施工类项目。',
      category: 'company',
      excerpt: '把公开可检索的中标和项目记录整理成官网可用表述。',
      publishedAt: '2026-05-05T00:00:00.000Z',
      slug: 'public-project-records',
      title: '公开项目记录：电力设施、现场维护与建筑工程',
    },
    {
      body: '公开资质信息显示，公司持有 D221023703 资质证书，包含建筑工程施工总承包二级、电力工程施工总承包二级等信息，有效期至 2029 年 7 月 23 日。国家能源局东北监管局公告中，也可以看到东亚电力建设有限公司承装（修、试）电力设施许可登记事项变更记录。\n\n技术侧，公司名下公开专利 CN215010107U 为“给铁路电力机车供电的光伏和风力互补发电隧道”，涉及在铁路隧道场景中利用光伏和风力发电，为电力机车供电并减少土地占用。\n\n官网可据此突出“电力工程施工、电气安装、电力设施检测维修、新能源技术应用”四类关键词，既真实，也比原来的泛化文案更贴近企业本身。',
      category: 'technology',
      excerpt: '资质与公开专利共同支撑电力工程和新能源应用方向。',
      publishedAt: '2026-05-04T00:00:00.000Z',
      slug: 'qualification-and-renewable-technology',
      title: '资质与新能源技术：从电力工程到风光互补应用',
    },
  ],
}
